theme: jekyll-theme-cayman
title: infomapecology--a package for running Infomap, inspired by ecological networks
description: The package contains functions that prepare monolayer and multilayer networks
for analysis with Infomap, run Infomap from within R and parse the results
back to R. Also includes standardized objects to store and further analyze
monolayer and multilayer networks. The package is inspired by analysis of
ecological networks but is suitable for other areas of research as well.
url: https://ecological-complexity-lab.github.io/infomap_ecology_package/
include: 
    _pages
    _layouts