---
title: "Install Infomap and infomapecology"
output:
  html_document: 
    fig_height: 6
    fig_width: 9
    theme: flatly
    code_folding: show
    toc: true
    toc_float:
      collapsed: false
      number_sections: true
---

```{r klippy, echo=FALSE, include=TRUE}
# Use this to add a copy-code buttong
klippy::klippy(position = c('top', 'right'), color = 'darkred')
```

<br>
<br>

# 1. Install the R package
The package was built under R 4.1 and depends on other packages.

```R
# Install  (if not installed) and load necessary packages
package.list=c("emln","attempt", "cowplot", "igraph", "ggalluvial","magrittr","vegan", "dplyr","readr","ggplot2","stringr","tibble","tidyr","rlang","igraph","bipartite")
loaded <-  package.list %in% .packages()
package.list <-  package.list[!loaded]
installed <-  package.list %in% .packages(TRUE)
if (!all(installed)) install.packages(package.list[!installed], repos="http://cran.rstudio.com/")

# Install infomapecology 
devtools::install_github('Ecological-Complexity-Lab/infomap_ecology_package', force=T)
library(infomapecology)

# Check the version.
packageDescription('infomapecology')
```

<br>
<br>

# 2. Install Infomap
We use Infomap version 2.x as a stand-alone file. We are working on integrating Infomap directly intro R.

<br>

## MacOS (Linux should be similar)
### 1. In the terminal run:
* `xcode-select --install`
* For OpenMP support
  * Install homebrew as specified in [https://brew.sh](https://brew.sh). This will take a while.
  * install packages: `brew install libomp`.

### 2. Then either:
Install Infomap via the `install_infomap` function in the package as below. Avoid folder names with spaces or non-english lettes.

```R
setwd('where your Infomap file and R script will live')
install_infomap()

# Check Infomap is running
setwd('where your Infomap file and R script now live')
check_infomap() # Make sure file can be run correctly. Should return TRUE
```

or download a binary from [here](https://github.com/mapequation/infomap/releases/latest) and put the file in the working folder.

<br>

## Windows

Install Infomap via the `install_infomap` function in the package as below. Avoid folder names with spaces or non-english lettes.

```R
setwd('where your Infomap file and R script will live')
install_infomap()

# Check Infomap is running
setwd('where your Infomap file and R script now live')
check_infomap() # Make sure file can be run correctly. Should return TRUE
```

or download a binary from [here](https://github.com/mapequation/infomap/releases/latest) and put the file in the working folder.


**Important notes:**

1. The best practice is to compile Infomap under the file name "Infomap" and place it in the
same working folder in which the R code is run.

2. Other ways to install: [https://www.mapequation.org/infomap/#Install](https://www.mapequation.org/infomap/#Install)
